= RRB API
Powered By Dongwhwan, https://github.com/hwanld
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 1
:sectlinks:


[[Bags-save]]
== Bags-save

operation::Bags-save[snippets='http-request,request-headers,http-response,response-fields']

---

[[Bags-Renting]]
== Bags-Renting

operation::Bags-Renting[snippets='http-request,request-headers,request-fields,request-body,http-response,response-body,response-fields']

---

[[Bags-Renting-AlreadyRentedException]]
== Bags-Renting-AlreadyRentedException

operation::Bags-Renting-AlreadyRentedException[snippets='http-request,request-headers,request-fields,request-body,http-response,response-body,response-fields']

---

[[Bags-RequestReturning]]
== Bags-RequestReturning

operation::Bags-RequestReturning[snippets='http-request,request-headers,request-fields,request-body,http-response,response-body,response-fields']

---

[[Bags-RequestReturning-ReturnRequestUserMismatchException]]
== Bags-RequestReturning-ReturnRequestUserMismatchException

operation::Bags-RequestReturning-ReturnRequestUserMismatchException[snippets='http-request,request-headers,request-fields,request-body,http-response,response-body,response-fields']

---

[[Bags-Returing]]
== Bags-Returning

operation::Bags-Returning[snippets='http-request,request-headers,path-parameters,request-body,http-response,response-body,response-fields']

---

[[Bags-findById]]
== Bags-findById

operation::Bags-findById[snippets='http-request,request-headers,path-parameters,request-body,http-response,response-body,response-fields']