= RRB API
Powered By Dongwhwan, https://github.com/wkazxf
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 1
:sectlinks:


[[Users-checkUserExist-True]]
== Users-checkUserExist-True

operation::Users-checkUserExist-True[snippets='http-request,request-body,http-response,response-body']

---

[[Users-checkUserExist-False]]
== Users-checkUserExist-False

operation::Users-checkUserExist-False[snippets='http-request,request-body,http-response,response-body']

---

[[Users-TestingToken-WithUserRole-Withv1Method]]
== Users-TestingToken-WithUserRole-Withv1Method

operation::Users-TestingToken-WithUserRole-Withv1Method[snippets='http-request,request-headers,request-body,http-response,response-body']


---

[[Users-TestingToken-WithUserRole-Withv3Method]]
== Users-TestingToken-WithUserRole-Withv3Method

operation::Users-TestingToken-WithUserRole-Withv3Method[snippets='http-request,request-headers,request-body,http-response,response-body']

---

[[Users-TestingToken-WithAdminRole-Withv1Method]]
== Users-TestingToken-WithAdminRole-Withv1Method

operation::Users-TestingToken-WithAdminRole-Withv1Method[snippets='http-request,request-headers,request-body,http-response,response-body']

---

[[Users-TestingToken-WithAdminRole-Withv3Method]]
== Users-TestingToken-WithAdminRole-Withv3Method

operation::Users-TestingToken-WithAdminRole-Withv3Method[snippets='http-request,request-headers,request-body,http-response,response-body']
