= RRB API
Powered By Dongwhwan, https://github.com/wkazxf
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 1
:sectlinks:


[[Users-save]]
== Users-save

operation::Users-save[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-save-admin]]
== Users-save-admin

operation::Users-save-admin[snippets='http-request,request-fields,http-response,response-fields']
---

[[Users-save-DuplicatedUserSaveException]]
== Users-save-DuplicatedUserSaveException

operation::Users-save-DuplicatedUserSaveException[snippets='http-request,request-fields,http-response,response-fields']

[[Users-login]]
== Users-login

operation::Users-login[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-login-UsersIdOrPasswordInvalidException]]
== Users-login-UsersIdOrPasswordInvalidException

operation::Users-login-UsersIdOrPasswordInvalidException[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-checkUserExist-True]]
== Users-checkUserExist-True

operation::Users-checkUserExist-True[snippets='http-request,path-parameters,http-response']

---

[[Users-checkUserExist-False]]
== Users-checkUserExist-False

operation::Users-checkUserExist-False[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-checkNicknameExist-True]]
== Users-checkNicknameExist-True

operation::Users-checkNicknameExist-True[snippets='http-request,path-parameters,http-response']

---

[[Users-checkNicknameExist-False]]
== Users-checkNicknameExist-False

operation::Users-checkNicknameExist-False[snippets='http-request,path-parameters,http-response,response-fields']

