= RRB API
Powered By Dongwhwan, https://github.com/wkazxf
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 1
:sectlinks:


[[Users-save]]
== Users-save

operation::Users-save[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-save-admin]]
== Users-save-admin

operation::Users-save-admin[snippets='http-request,request-fields,http-response,response-fields']
---

[[Users-save-DuplicatedUserSaveException]]
== Users-save-DuplicatedUserSaveException

operation::Users-save-DuplicatedUserSaveException[snippets='http-request,request-fields,http-response,response-fields']

[[Users-login]]
== Users-login

operation::Users-login[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-login-UsersIdOrPasswordInvalidException]]
== Users-login-UsersIdOrPasswordInvalidException

operation::Users-login-UsersIdOrPasswordInvalidException[snippets='http-request,request-fields,http-response,response-fields']

---

[[Users-checkUserExist]]
== Users-checkUserExist

operation::Users-checkUserExist[snippets='http-request,path-parameters,http-response']

---

[[Users-checkUserExist-UsersIDAlreadyExistException]]
== Users-checkUserExist-UsersIDAlreadyExistException

operation::Users-checkUserExist-UsersIdAlreadyExistException[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-checkNicknameExist]]
== Users-checkNicknameExist

operation::Users-checkNicknameExist[snippets='http-request,path-parameters,http-response']

---

[[Users-checkNicknameExist-NicknameAlreadyExistException]]
== Users-checkNicknameExist-NicknameAlreadyExistException

operation::Users-checkNicknameExist-NicknameAlreadyExistException[snippets='http-request,path-parameters,http-response,response-fields']

